# Generated by Django 2.2 on 2021-12-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('other', 'OTHER'), ('phones', 'Phones'), ('hdd', 'HDD')], default='other', max_length=100, verbose_name='Категория'),
        ),
    ]
