# Generated by Django 2.2 on 2021-12-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211223_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('other', 'Other'), ('phones', 'Phones'), ('headPhones', 'Head phones'), ('memory', 'Memory'), ('hdd', 'HDD')], default='other', max_length=100, verbose_name='Категория'),
        ),
    ]
