# Generated by Django 2.2 on 2021-12-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211223_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
